// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mdlyglpbdqvgwnayumhh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1kbHlnbHBiZHF2Z3duYXl1bWhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMTkxNDksImV4cCI6MjA2NDY5NTE0OX0.j0qp4ewdvt7IefarpcISAqqGZAq8bQl-1A5ho34FK_E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);